# Generated by Django 2.2 on 2019-07-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank='False', null='True', upload_to=''),
        ),
    ]
