# Generated by Django 2.2 on 2019-07-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190731_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank='False', null='True', upload_to='posts'),
        ),
    ]
